fix: homepage - use `Link` for internal links
themesberg/flowbite-react pull request #1001
Opened 2023-09-26 16:26 UTC by SutuSebastian

- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Use NextJS `Link` component for internal routes. Avoid full page refresh and improve UX.

### Before

https://github.com/themesberg/flowbite-react/assets/41998826/f971741b-80f3-4aca-89c0-a1dc1764e95a

### After

https://github.com/themesberg/flowbite-react/assets/41998826/b52b5211-7335-4a58-b7b3-3ebee3a731b3

2023-09-26 16:31 UTC, rluders requested changes

2023-09-26 16:34 UTC, SutuSebastian commented on app/page.tsx
> +                    <Link href="/docs/getting-started/introduction" tabIndex={-1}>
Already discussed in Discord in the `react-library`, TS throws errors when doing that, it does not properly infer & extend the `Link` component from NextJS. That is the reason I made it like this.

Do u think we should fix the underlying issue with TS first? Luckily this is the only place `href` props is used that is visible to the user.

2023-09-26 16:35 UTC, SutuSebastian commented on app/page.tsx
> +                    <Link href="/docs/getting-started/introduction" tabIndex={-1}>
<img width="1283" alt="Screenshot 2023-09-26 at 19 35 30" src="https://github.com/themesberg/flowbite-react/assets/41998826/b6474493-8e9b-4b30-a1f7-c28d137e9e43">

2023-09-30 07:32 UTC, rluders commented on app/page.tsx
> +                    <Link href="/docs/getting-started/introduction" tabIndex={-1}>
As we discussed, I think that we should first fix the button. I'm converting this PR to draft till we get the fix.

2024-01-24 00:20 UTC, nigellima commented on app/page.tsx
> +                    <Link href="/docs/getting-started/introduction" tabIndex={-1}>
#1244 should fix this now @SutuSebastian @rluders

2024-01-24 07:33 UTC, SutuSebastian commented
deprecated by #1246, this one is too outdated.

2024-01-24 07:33 UTC, closed without merging

2024-01-24 07:34 UTC, SutuSebastian commented on app/page.tsx
> +                    <Link href="/docs/getting-started/introduction" tabIndex={-1}>
will push the fixes in #1246.