fix: button with a label
themesberg/flowbite-react pull request #1041
Opened 2023-10-03 23:34 UTC by MateoWartelle

- [X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.
#1020 

change check to show children and label independently

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

2023-10-04 07:33 UTC, rluders requested changes

2023-10-04 07:33 UTC, rluders commented on src/components/Button/Button.tsx
> +            ''
`null`

2023-10-04 07:33 UTC, rluders commented on src/components/Button/Button.tsx
> +          {typeof label !== 'undefined' ? (
What would happen if `label=""` or `<Button label>Test</Button>`?

2023-10-08 14:38 UTC, SutuSebastian commented on src/components/Button/Button.tsx
> +          {children ?? children}
if `children` is simply rendering itself, then this is redundant.

Instead, simply render it like `{children}`, react will take care if its `null` or `undefined` and not render anything, else render the node.

2023-12-31 00:52 UTC, closed without merging