docs(checkbox): standalone page for checkbox documentation
themesberg/flowbite-react pull request #1130
Opened 2023-11-13 01:58 UTC by MateoWartelle

- [X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

To create separate pages for /forms/* documentations to match flowbite.

I had tried this previously but the branch was too far gone to continue (merge conflicts).

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

2023-11-13 02:17 UTC, MateoWartelle commented
werid.. I can't tell what is wrong with the preview. The build passes locally. 

` ✓ Generating static pages (43/43) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    1.93 kB         217 kB
├ ○ /_not-found                          962 B            92 kB
└ ● /docs/[[...slug]]                    30 kB           214 kB
    ├ /docs/components/accordion
    ├ /docs/components/alert
    ├ /docs/components/avatar
    └ [+36 more paths]
+ First Load JS shared by all            91.1 kB
  ├ chunks/472-48e99746bd29f5a8.js       34.7 kB
  ├ chunks/fd9d1056-4e50bd5b75371e6d.js  53.8 kB
  ├ chunks/main-app-657973b50a7bf24c.js  282 B
  └ chunks/webpack-c7746c740a8989b6.js   2.3 kB


○  (Static)  prerendered as static HTML
●  (SSG)     prerendered as static HTML (uses getStaticProps)

✨  Done in 24.49s.`

2023-11-13 23:53 UTC, MateoWartelle commented
@rluders can you check and Ill fix it? I can't tell why the preview failed.

2023-11-14 06:40 UTC, SutuSebastian commented on data/docs-sidebar.ts
> +      { title: 'Checkbox', href: '/docs/forms/checkbox', isNew: false },
`isNew: false` is redundant since its an optional property

2023-11-14 06:43 UTC, SutuSebastian approved these changes
this is nice!

2023-11-14 06:45 UTC, SutuSebastian commented on examples/checkbox/checkbox.listGroup.tsx
> +  githubSlug: 'checkbox/checkbox.listgroup.tsx',
rename `listgroup` to `listGroup`

2023-11-14 06:46 UTC, SutuSebastian commented on examples/checkbox/index.ts
> +export { listGroup } from './checkbox.listgroup';
rename `listgroup` to `listGroup`

2023-11-14 06:47 UTC, SutuSebastian commented
> weird.. I can't tell what is wrong with the preview. The build passes locally.
> 
> ```
> ✓ Generating static pages (43/43) 
> ✓ Collecting build traces    
> ✓ Finalizing page optimization    
> 
> Route (app)                              Size     First Load JS
> ┌ ○ /                                    1.93 kB         217 kB
> ├ ○ /_not-found                          962 B            92 kB
> └ ● /docs/[[...slug]]                    30 kB           214 kB
>     ├ /docs/components/accordion
>     ├ /docs/components/alert
>     ├ /docs/components/avatar
>     └ [+36 more paths]
> + First Load JS shared by all            91.1 kB
>   ├ chunks/472-48e99746bd29f5a8.js       34.7 kB
>   ├ chunks/fd9d1056-4e50bd5b75371e6d.js  53.8 kB
>   ├ chunks/main-app-657973b50a7bf24c.js  282 B
>   └ chunks/webpack-c7746c740a8989b6.js   2.3 kB
> 
> 
> ○  (Static)  prerendered as static HTML
> ●  (SSG)     prerendered as static HTML (uses getStaticProps)
> 
> ✨  Done in 24.49s.
> ```

This passes locally for u probably because u renamed the file afterwards from `listgroup` (lowercase) to `listGroup` (camelcase) and the IDE and git did not catch it (it happens quite often, don't worry).

Build fails due to:
```
./examples/checkbox/index.ts
Module not found: Can't resolve './checkbox.listgroup'
```

I left comments where it should be fixed.

2023-11-14 13:21 UTC, MateoWartelle commented
> > weird.. I can't tell what is wrong with the preview. The build passes locally.
> > ```
> > ✓ Generating static pages (43/43) 
> > ✓ Collecting build traces    
> > ✓ Finalizing page optimization    
> > 
> > Route (app)                              Size     First Load JS
> > ┌ ○ /                                    1.93 kB         217 kB
> > ├ ○ /_not-found                          962 B            92 kB
> > └ ● /docs/[[...slug]]                    30 kB           214 kB
> >     ├ /docs/components/accordion
> >     ├ /docs/components/alert
> >     ├ /docs/components/avatar
> >     └ [+36 more paths]
> > + First Load JS shared by all            91.1 kB
> >   ├ chunks/472-48e99746bd29f5a8.js       34.7 kB
> >   ├ chunks/fd9d1056-4e50bd5b75371e6d.js  53.8 kB
> >   ├ chunks/main-app-657973b50a7bf24c.js  282 B
> >   └ chunks/webpack-c7746c740a8989b6.js   2.3 kB
> > 
> > 
> > ○  (Static)  prerendered as static HTML
> > ●  (SSG)     prerendered as static HTML (uses getStaticProps)
> > 
> > ✨  Done in 24.49s.
> > ```
> 
> This passes locally for u probably because u renamed the file afterwards from `listgroup` (lowercase) to `listGroup` (camelcase) and the IDE and git did not catch it (it happens quite often, don't worry).
> 
> Build fails due to:
> 
> ```
> ./examples/checkbox/index.ts
> Module not found: Can't resolve './checkbox.listgroup'
> ```
> 
> I left comments where it should be fixed.

ahhh thank you.

2023-11-14 21:51 UTC, SutuSebastian commented
maybe we should remove the existing `checkbox` docs and examples which is under `components/forms/*` as we slowly migrate all of them and eventually deprecate for good `components/forms/*`

2023-11-14 21:57 UTC, SutuSebastian commented
the disabled state doesn't look like https://flowbite.com/docs/forms/checkbox/#disabled-state

react
<img width="903" alt="Screenshot 2023-11-14 at 23 55 50" src="https://github.com/themesberg/flowbite-react/assets/41998826/a84656d3-aa8d-4636-a114-4ee4ae85116b">

core
<img width="874" alt="Screenshot 2023-11-14 at 23 55 55" src="https://github.com/themesberg/flowbite-react/assets/41998826/35c686d9-5212-4e9c-a90f-40bef14c1622">

2023-11-14 21:57 UTC, SutuSebastian requested changes
the disabled state doesn't look like https://flowbite.com/docs/forms/checkbox/#disabled-state

react
<img width="903" alt="Screenshot 2023-11-14 at 23 55 50" src="https://github.com/themesberg/flowbite-react/assets/41998826/a84656d3-aa8d-4636-a114-4ee4ae85116b">

core
<img width="874" alt="Screenshot 2023-11-14 at 23 55 55" src="https://github.com/themesberg/flowbite-react/assets/41998826/35c686d9-5212-4e9c-a90f-40bef14c1622">

2023-11-14 22:01 UTC, SutuSebastian commented on examples/checkbox/checkbox.horizontalListGroup.tsx
in the core library clicking the entire section triggers a checked/unchecked action.



https://github.com/themesberg/flowbite-react/assets/41998826/c47e46c1-6f17-445d-8475-ae86076e9d4b

2023-11-14 22:03 UTC, SutuSebastian commented on examples/checkbox/checkbox.colors.tsx
> +const code = `
code here is incorrect, it should be the one below in the function

2023-11-14 22:06 UTC, SutuSebastian commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
I think orange is missing

2023-11-14 22:32 UTC, MateoWartelle commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
orange is not in FlowBiteColors ?

2023-11-14 22:57 UTC, MateoWartelle commented
> the disabled state doesn't look like https://flowbite.com/docs/forms/checkbox/#disabled-state
> 
> react <img alt="Screenshot 2023-11-14 at 23 55 50" width="903" src="https://user-images.githubusercontent.com/41998826/282942584-a84656d3-aa8d-4636-a114-4ee4ae85116b.png">
> 
> core <img alt="Screenshot 2023-11-14 at 23 55 55" width="874" src="https://user-images.githubusercontent.com/41998826/282942673-35c686d9-5212-4e9c-a90f-40bef14c1622.png">

ohh I see Label was not disabled.

2023-11-15 07:22 UTC, SutuSebastian commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
oh that's true, but why isn't it 🤔

2023-11-15 08:00 UTC, rluders commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
There are all the flowbite colors:
https://flowbite.com/docs/customize/colors/

However, it extends the TailwindCSS... so it means that...
https://tailwindcss.com/docs/customizing-colors

☝️ these colors (if now overwriten) are also available.

2023-11-15 08:04 UTC, SutuSebastian commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
I see, gotcha! 🤝

2023-11-15 08:13 UTC, rluders commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
BTW, just one side note here if someone wants to create an issue for this (not asking to include on this PR), we should work to provide all colors to all the components, and improve the color interface `FlowbiteColors`, `TailwindColors`, `FlowbiteStateColors` (default, active, enable, disable)... I don't know. But, we need to create some standard interface that needs to be available to all the components. Needs some PoC/Proposal/Investigation, maybe not all components need all the colors, and in this case, we may need to find a way to inform it in the docs.

But as I said, I don't expect this to be fixed on this PR... But we need a very well-described issue for this. (ChatGPT?)

2023-11-15 08:20 UTC, SutuSebastian commented on examples/checkbox/checkbox.colors.tsx
> +      </div>
lets get to digging/brainstorming then

2023-11-18 23:21 UTC, MateoWartelle commented on examples/checkbox/checkbox.horizontalListGroup.tsx
I see, ok i will fix.

2023-11-24 08:19 UTC, rluders commented
@MateoWartelle @SutuSebastian I think that we are good to merge this one, right? Just need to rebase.

2023-11-24 08:54 UTC, SutuSebastian commented
> @MateoWartelle @SutuSebastian I think that we are good to merge this one, right? Just need to rebase.

I think some things broke down after rebase:
- sidebar does not contain the `checkbox` item anymore

<img width="244" alt="Screenshot 2023-11-24 at 10 53 14" src="https://github.com/themesberg/flowbite-react/assets/41998826/1e7f4a6a-8577-4bbc-8760-eef0896421ac">

2023-11-24 08:57 UTC, SutuSebastian commented
> @MateoWartelle @SutuSebastian I think that we are good to merge this one, right? Just need to rebase.

There's still this issue that hasn't been resolved:

https://github.com/themesberg/flowbite-react/assets/41998826/c47e46c1-6f17-445d-8475-ae86076e9d4b

and it applies to both `Checkbox list group ` and `Horizontal list group `

2023-11-24 15:29 UTC, rluders commented
I notice that when the checkbox is marked by default to be `checked` it cannot be `uncheked` by clicking on it. Is it just a documentation thing? Is this expected?

2023-11-24 21:23 UTC, SutuSebastian requested changes

2023-11-24 21:23 UTC, SutuSebastian commented on examples/checkbox/checkbox.disabled.tsx
> +        <Label htmlFor="disabled-checked-state-checkbox" disabled>Disabled defaultChecked</Label>
small mistake here, revert to `Disabled checked`

2023-11-24 21:23 UTC, SutuSebastian commented on examples/checkbox/checkbox.disabled.tsx
> +        <Label htmlFor="disabled-checked-state-checkbox" disabled>Disabled defaultChecked</Label>
revert to `Disabled checked`

2023-11-24 21:38 UTC, SutuSebastian commented
Some minor differences:

`Checkbox list group`

Core
<img width="380" alt="Screenshot 2023-11-24 at 23 25 56" src="https://github.com/themesberg/flowbite-react/assets/41998826/64875924-2917-4f6d-ab99-2e04f80715e1">

React
<img width="409" alt="Screenshot 2023-11-24 at 23 26 10" src="https://github.com/themesberg/flowbite-react/assets/41998826/222cb0bc-f3b8-42f6-9ec1-d041aaa1af08">

`Horizontal list group`

Core
<img width="849" alt="Screenshot 2023-11-24 at 23 27 04" src="https://github.com/themesberg/flowbite-react/assets/41998826/8cb48dad-15b1-411f-b5b0-3a8a7b7887

React
<img width="861" alt="Screenshot 2023-11-24 at 23 26 27" src="https://github.com/themesberg/flowbite-react/assets/41998826/24b4234c-a5cf-4185-8438-313ec8cc505d">
4f">

`Inline layout`

Core
<img width="857" alt="Screenshot 2023-11-24 at 23 28 11" src="https://github.com/themesberg/flowbite-react/assets/41998826/9d1aa9ea-b314-47a2-be51-9b7e6b60fd8f">

React
<img width="881" alt="Screenshot 2023-11-24 at 23 28 22" src="https://github.com/themesberg/flowbite-react/assets/41998826/057d835c-f370-482b-a794-99d6c3bec595">

`Advanced layout `

Core
<img width="295" alt="Screenshot 2023-11-24 at 23 37 00" src="https://github.com/themesberg/flowbite-react/assets/41998826/f105d969-e4be-4367-8f29-45670d89e21f">

React
<img width="301" alt="Screenshot 2023-11-24 at 23 37 06" src="https://github.com/themesberg/flowbite-react/assets/41998826/641d7485-c2f0-4132-96b1-2538f32cc76b">

2023-12-31 00:52 UTC, closed without merging