feature(component): Change `Accordion`s to close inactive panels, resolves #159
themesberg/flowbite-react pull request #163
Opened 2022-05-29 01:37 UTC by tulup-conner

## Breaking changes

`Accordion`s used to let more than one `Accordion.Panel` be open at once. Now, only the most recently clicked panel will be open.

To override this behavior, specify `<Accordion alwaysOpen>`.

See the [Flowbite Accordion docs](https://flowbite.com/docs/components/accordion/) - notably, the `Default accordion` and `Always open` examples

## Features

- [x] [feature(component): Change Accordions to close inactive panels, res…](https://github.com/themesberg/flowbite-react/commit/58ab0f1b13732d691ee63542343d4bad8766625d)
- [x] [feature(story): Add missing Accordion stories](https://github.com/themesberg/flowbite-react/commit/e6d7e2d1927e98bedf233c15384ed3f9e0e1d4de)

## Tests

### Unit

- [x] [test(component): Add numerous unit tests for Accordions](https://github.com/themesberg/flowbite-react/commit/7e54b587539cd438b9ce9c99e56cd3e96201d14f)

2022-05-29 08:01 UTC, rluders requested changes
About boolean values, read:
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2022-05-29 08:01 UTC, rluders commented on src/lib/components/Accordion/AccordionContent.tsx
> +  const { open } = useAccordionContext();
isOpen

2022-05-29 08:01 UTC, rluders commented on src/lib/components/Accordion/AccordionPanel.tsx
> +  const [open, setOpen] = useState(props.open);
isOpen

2022-05-29 08:01 UTC, rluders commented on src/lib/components/Accordion/AccordionTitle.tsx
> +  const { arrowIcon: ArrowIcon, flush, open, setOpen } = useAccordionContext();
isOpen

2022-05-29 08:07 UTC, tulup-conner commented
> About boolean values, read: https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

Sure, I do that in my own projects, but pretty much every boolean in the Flowbite API doesn't start with is :)

I'm happy to change to that convention universally.

2022-05-29 08:15 UTC, tulup-conner commented
Let me know if you want me to make the change still. The API for Accordions currently accepts an attribute `open`, not `isOpen`, which is my motivation.

2022-05-29 08:36 UTC, rluders commented
I think that we can keep the API, but change the state. Can't we? Mostly, 'cause I think that `API != state`.

2022-05-29 09:11 UTC, tulup-conner commented
@rluders Absolutely, I'll change these and I'll make sure to use is for variable booleans

2022-06-02 13:16 UTC, rluders approved these changes

2022-06-02 13:17 UTC, merged