feature(component):Rewrite Progress to use themes, resolves #141
themesberg/flowbite-react pull request #172
Opened 2022-05-31 16:07 UTC by mouracamila

closes #141

2022-06-02 14:38 UTC, mouracamila commented
please @tulup-conner Could you take a look this?  (around the a11y)

2022-06-02 21:05 UTC, tulup-conner requested changes

2022-06-03 15:06 UTC, rluders requested changes

2022-06-03 15:06 UTC, rluders commented on src/lib/components/Progress/index.tsx
> +        <div className={classNames(theme.base, theme.size[size])}>
You can remove the `classNames` function here.

2022-06-03 15:06 UTC, rluders commented on src/lib/components/Progress/index.tsx
> +            className={classNames(theme.bar, theme.color[color], theme.size[size])}
You can remove the `classNames` function here.

2022-06-03 15:06 UTC, rluders commented on src/lib/components/Progress/index.tsx
>  import classNames from 'classnames';
You don't need the classNames import

2022-06-16 14:19 UTC, merged