Avatar component
themesberg/flowbite-react pull request #18
Opened 2022-04-10 17:04 UTC by mouracamila

Hi! This PR adds the avatar component 

/closes #3

2022-04-11 09:38 UTC, bacali95 commented
Hello @mouracamila, thanks for your contribution :smile: 
I assume this PR is still in progress, so please set it as `Ready for review` once you are done.

2022-04-12 12:44 UTC, mouracamila commented
Hi, @bacali95 I'd like to ask for a review. 
It still needs two types of avatar to build, dropdown and stacked, this is alit bit more complex, I believe this is a need made in other Issues

2022-04-13 09:17 UTC, bacali95 requested changes
Hey @mouracamila thanks again for your contribution, this looks good for me, I just left one minor comment if you can check it :smile: 
About the dropdown feature, I will do it in this PR so we have everything covered at once, I hope you don't mind that.

2022-04-13 09:17 UTC, bacali95 commented on src/components/Avatar.tsx
> +              'rounded-full p-1 ring-2 ring-gray-300 dark:ring-gray-500': bordered,
I think we can have a bordered avatar but not rounded, right?

2022-04-13 13:10 UTC, bacali95 approved these changes

2022-04-13 13:12 UTC, merged