Prevent scrollbars around dynamic tables
themesberg/flowbite-react pull request #608
Opened 2023-02-17 23:59 UTC by multiwebinc

## Description

This moves the background color and border radius to the cells and places a div under the table for the box shadow effect. That way if a table is modified (rows or columns added or removed) or if the screen resolution changes, it won't create scrollbars around the table.

Fixes #605

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Just tested by trying it out

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-02-21 02:59 UTC, tulup-conner commented
I love this idea, but we don't want to ship custom CSS. Can you find a way to accomplish this in Tailwind CSS via the theme instead of creating a stylesheet file?

2023-02-22 04:54 UTC, multiwebinc commented
@tulup-conner What about like this?

2023-02-22 07:20 UTC, tulup-conner commented
We will want a solution using Tailwind CSS purely, which has support for custom selectors like these. Inline CSS has other negative implications for users, e.g., it will break Content Security Policies.

2023-02-22 08:12 UTC, rluders requested changes

2023-02-22 08:12 UTC, rluders commented on src/lib/components/Table/Table.tsx
> +      <style jsx>{`
I don't think that we want to do this. You must use TailwindCSS classes. Flowbite is a TailwindCSS-based component library, there is no point to use CSS or SASS or whatever.

2023-02-22 08:13 UTC, rluders commented on src/lib/components/Table/Table.tsx
> +      <style jsx>{`
https://tailwindcss.com/docs/utility-first

2023-02-22 16:51 UTC, multiwebinc commented
@rluders @tulup-conner I was looking into the [`group-{modifier}` class](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state), however I need 2 levels of groups, because it needs to select the first/last child of `<table>` combined with the first/last `<td>` or `<th>`. Would you be opposed to using https://www.npmjs.com/package/tailwindcss-scoped-groups? 

If not, the only thing I can do with tailwind is style the top borders in `<thead>` (if there is one) and bottom borders of `<tfoot>` (if there is one). Without knowing whether `<tbody>` is the first or last child, you can't add a border radius to any of the cells in it. Unless maybe I add two more props to the `<Table>` component - `headless` and `footless` and if either of these are `true`, it will add the border radius to the corresponding tbody cells.

2023-02-22 17:38 UTC, multiwebinc commented
@rluders @tulup-conner Ok, I think that's it. No stylesheets. I didn't know about nested groups, so I didn't think it was possible without stylesheets.

2023-02-22 20:27 UTC, rluders commented
@multiwebinc could you sync your branch with the `main` branch? It has some conflicts because the theme structure was changed. So, you may have to adjust a few things on your PR.

2023-02-22 21:53 UTC, multiwebinc commented
@rluders What do you think, would it make sense to move the `table.cell` interface to `table.body.cell` to avoid confusion with `table.head.cell`?

2023-02-23 09:05 UTC, rluders commented
> @rluders What do you think, would it make sense to move the `table.cell` interface to `table.body.cell` to avoid confusion with `table.head.cell`?

I think that it makes sense. WDYT, @tulup-conner ?

2023-04-17 18:56 UTC, rluders commented
Well, I can't see any reason to keep this one pending. I'm accepting it, @multiwebinc. Thank you!

2023-04-17 18:56 UTC, merged