Edit Floating.tsx
themesberg/flowbite-react pull request #623
Opened 2023-02-23 16:22 UTC by multiwebinc

## Description

When the window is resized, occasionally the tooltip creates horizontal scrolling. This PR sets the `left` attribute to `0` when the tooltip is closed.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested locally by use

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-03-05 18:05 UTC, tulup-conner requested changes

2023-03-05 18:05 UTC, tulup-conner commented on src/lib/components/Floating/Floating.tsx
> +            top: open ? y ?? ' ' : 0,
We can just change these to open ? y : 0 now, right?

2023-04-06 13:46 UTC, rluders commented
Can we drop this one in favor of #683? @multiwebinc @tulup-conner

2023-04-06 15:51 UTC, multiwebinc commented
@rluders I'm off for the weekend. I'll take a look at it next week unless someone else wants to. But I think they are probably complimantary because I didn't alter the styles much in #683.

2023-04-17 18:58 UTC, rluders commented
> @rluders I'm off for the weekend. I'll take a look at it next week unless someone else wants to. But I think they are probably complimantary because I didn't alter the styles much in #683.

Not being pushy on this one, but... any update?

2023-04-17 20:29 UTC, multiwebinc commented
@rluders Sorry for the delay. Yes, I see that this can just be closed now in favor of #683.

2023-04-17 20:29 UTC, closed without merging