feat(build): Upgrade `@popperjs/*` to `@floating-ui/react-*`
themesberg/flowbite-react pull request #67
Opened 2022-04-27 08:52 UTC by tulup-conner

[Floating UI]() is the next evolution of [Popper](). 

We currently have a strange bug on Chromium causing `Dropdown`s/`Tooltip`s to be  misaligned with their target. This upgrade happens to resolve #57, as a bonus!

Because `Tooltip` is used by `Dropdown`, both components have been upgraded.

2022-04-27 08:54 UTC, tulup-conner commented
I still need to fix an issue where the tooltip arrow can obstruct content inside the tooltip itself.

2022-04-27 08:58 UTC, tulup-conner commented
Ugh, it looks like the bug is still present, but *only* in Storybook, and *only* in Chromium browsers. Because the issue is isolated to Storybook, I'm more inclined it's a bug on their end. Will look into that more.

2022-04-29 09:35 UTC, rluders requested changes

2022-04-29 09:35 UTC, rluders commented on src/components/Tooltip/index.tsx
> +  if (placement === 'auto') {
```ts
middleware.push(placement === 'auto' ? autoPlacement() : flip());
```

2022-04-29 09:42 UTC, tulup-conner commented on src/components/Tooltip/index.tsx
> +  if (placement === 'auto') {
Derp, change on the way

2022-04-30 14:28 UTC, rluders commented
@tulup-conner may I ask one 'related change'? Could you please change the decorator in this file:
https://github.com/themesberg/flowbite-react/blob/0b6bb5fbbaa160d02204d59d0c936e5572eba21f/.storybook/preview.js#L3

It needs to be something like this:
```ts
export const decorators = [
  (Story) => (
    <>
      <Style />
      <div className="flex h-screen justify-center items-center">
        <div>
          <Story />
        </div>
      </div>
    </>
  ),
];
```
The ideia is to centralize all components to the screen, so it would looks nice to preview it, and also 'cause I was having some "issues" (I know that it isn't an issue) to preview the placement to the tooptip when it when out of frame.

Otherwise it looks nice.

2022-05-01 00:21 UTC, tulup-conner commented
@rluders Done - I also added `<MemoryRouter>` as a wrapper because it is required for components that use `react-router-dom` `Link`. (Will be necessary to merge `Sidebar` stories in #69)

2022-05-02 07:25 UTC, merged