As button
themesberg/flowbite-react pull request #681
Opened 2023-03-29 17:05 UTC by AlfieJones

## Description

Adds a generic RenderAs component which allows for an as={} prop.

I have implemented this on the Button component but we can extend this further to other components.

I have left the href prop as is for now to avoid any breaking changes. However we could remove this as using as={"a"} achieves the same result

Fixes https://github.com/themesberg/flowbite-react/issues/655

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change contains documentation update

## Breaking changes

Please document the breaking changes if suitable.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-03-29 17:08 UTC, AlfieJones commented
@rluders @tulup-conner Any thoughts/suggestions on this implementation?

2023-04-05 08:32 UTC, rluders requested changes

2023-04-05 08:32 UTC, rluders commented on src/lib/components/Modal/Modal.spec.tsx
> +  it.skip('should automatically focus the `TextInput` inside the `Modal` when its opened', async () => {
I don't get this change.

2023-04-05 08:32 UTC, rluders commented on src/lib/helpers/renderAs.tsx
> +export function RenderAs<TTag extends ElementType>({
I like the idea of this component. My two cents here:

- Rename the filename to `RenderAs.tsx`
- Create some unit tests to test it

2023-06-05 19:46 UTC, nigellima commented
Any idea on when this could be merged? Or is there anything I can help with to move this forward?

2023-06-05 20:01 UTC, rluders commented
> Any idea on when this could be merged? Or is there anything I can help with to move this forward?
> @rluders

It needs to be rebased and a little bit more of work. I think that the changes weren’t made yet. So, if you or anyone is interested in co-authoring this, go ahead.

2023-06-06 22:57 UTC, tulup-conner commented
Yeah, we need this to be rebased `git fetch upstream main && git rebase -i upstream/main` at a minimum. The Button component changes are complex. There's also a lot of unfinished TypeScript in here that needs to be properly buttoned up. For example, we're not going to merge changes with casts to any and never - those need to be looked into.

If all we want is to change `<button>` to be able to be any other HTML element, I think we've overdone it a bit here. There are other components that support this, and we should follow their precedent. For example, https://github.com/themesberg/flowbite-react/blob/main/src/components/Sidebar/SidebarItem.tsx#L83

2024-03-29 13:14 UTC, SutuSebastian commented
Fixed in recent PR's.

2024-03-29 13:14 UTC, closed without merging