feat(dropdown): add disabled to dropdown
themesberg/flowbite-react pull request #727
Opened 2023-05-02 12:20 UTC by paghar

#539

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change contains documentation update

## Breaking changes

Please document the breaking changes if suitable.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-04 14:38 UTC, tulup-conner commented
Please add at least one test case for this verifying the disabled behavior.

2023-05-08 08:00 UTC, paghar commented
@tulup-conner  I added test case. Please check it.

2023-05-26 04:43 UTC, tulup-conner requested changes
Thank you! Can you rebase and move these changes to src/theme.ts? We just changed up our repository pretty substantially. You can see the new contributing guide here: https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md

If you aren't comfortable rebasing, let me know and I'll be happy to do so for you.

2023-05-28 10:26 UTC, paghar commented
@tulup-conner I will do it.

2023-05-29 11:17 UTC, paghar commented on src/components/Dropdown/Dropdown.tsx
> +    disabled,
Done

2023-05-29 11:17 UTC, paghar commented on src/components/Floating/Floating.tsx
> +  disabled,
@rluders Done

2023-05-29 12:09 UTC, rluders approved these changes
lgtm

2023-05-29 12:10 UTC, rluders commented
@tulup-conner up to you know.

2023-06-16 08:49 UTC, rluders commented
@paghar can you rebase this one with `main` branch? I think that there are some conflicts to be solved. Once done, ping me than I can get it merged. Thanks.

2023-06-18 12:25 UTC, rluders commented
@paghar Please, revert your merge commit and use rebase instead of merge to update your branch.

2023-06-21 04:46 UTC, tulup-conner commented
Let me know when this has been updated and I will give it another pass

2023-07-16 18:33 UTC, rluders commented
This was completed by #840

2023-07-16 18:33 UTC, closed without merging