feat(data drawer sidebar): data Drawer Sidebar
themesberg/flowbite-react pull request #733
Opened 2023-05-09 12:50 UTC by goswamianshuman

the feature was required to be added in a issue with title `Add full "drawer" support to Sidebar component #721`

"enhance #721"

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change contains documentation update

## Breaking changes

Please document the breaking changes if suitable.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-09 13:00 UTC, rluders requested changes
Hey, @goswamianshuman thanks... But, TBH, I'm not even sure what I'm looking at. Why did you duplicate the sidebar component? Is there any particular reason to create a new component that duplicates an existing component? I don't think so... Am I missing something here?

2023-05-09 13:12 UTC, goswamianshuman commented on src/lib/components/Modal/Modal.spec.tsx
> +  // it('should automatically focus the `TextInput` inside the `Modal` when its opened', async () => {
> But... why?

let me check it once I think I missed something here.

2023-05-09 18:08 UTC, goswamianshuman commented on src/lib/components/Modal/Modal.spec.tsx
> +  // it('should automatically focus the `TextInput` inside the `Modal` when its opened', async () => {
Hello, @rluders I just changed the changes in modal.spec.tsx back to the original in the local system there were getting some errors while building but I tried it again and they worked without any problem I think you can further check the other things and let me know if there is a need to change anything else. 

also, let me know about the above explanation for updating and grouping the elements into a new folder will this work? if not then I can change the names.

2023-05-09 18:34 UTC, rluders commented on src/lib/components/Modal/Modal.spec.tsx
> +  // it('should automatically focus the `TextInput` inside the `Modal` when its opened', async () => {
Well, I'm not convinced about this one. I think that the best way to make the `Sidebar` works as a drawer is to simply use the implementation that is in WIP (#664), and simply use the `Sidebar` as the `Drawer`content.

Currently, this is just a duplication of code that we already have... Doesn't make sense, IMHO. So, for me, it doesn't work.

@tulup-conner WDYT?

2023-05-26 04:41 UTC, tulup-conner commented
Thank you for the submission, but it needs a lot more work. 

We also just totally revamped our development server, and you may want to read the [new contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md). A few things:

1. Since we just changed almost everything in the development server, you need to rebase this branch with the latest changes. Let me know if you can't do that, and I'll do so for you
2. You need to add a new page in the docs with the exact same examples found at https://flowbite.com/docs/components/drawer/
3. You can't duplicate all of the code from Sidebar to accomplish this. You should just create a `Sidebar` internally with `Drawer` and customize it with a theme to look like the Flowbite `Drawer`
5. The component should be in a directory just called `src/components/drawer`
6. There should be unit tests specific only to the `Drawer`, because what you're effectively doing is running all of the `Sidebar` unit tests twice for no reason. That would be things like making sure the body can't be scrolled when the `Drawer` is open

2023-05-26 15:04 UTC, closed without merging