fix(modal): fix modal portal render identity
themesberg/flowbite-react pull request #748
Opened 2023-05-16 12:47 UTC by myabeaver

BREAKING CHANGE: modal content is only rendered when show is true

fix #701

## Description

* `windowExists()` is enough to check if it is rendered on the client or not. Therefore I removed the `mounted` state.
* To fix the identity of the portal container, I removed `appendChild`. Which was called multiple times. I replaced it with the root itself, because `createPortal` already appends its content to the provided container (`root`).
* That `.toHaveFocus()` works i removed the `waitFor` and set removed `root={root}`. The `root` must be part of the screen DOM.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Breaking changes

* If `show` is false, then the content is not rendered anymore.
* `aria-hidden` is removed.
* The additional `<div />` (`containerRef`) is removed.

## How Has This Been Tested?

Should be tested in a Next.js server component.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-05-16 13:10 UTC, rluders commented on src/lib/components/Modal/Modal.tsx
> +  root.style.overflow = show ? 'hidden' : '';
Well... I think so.

2023-05-25 14:59 UTC, rluders commented
> @rluders This PR is perhaps more for discussion. I have removed parts of the old code which is not necessary.
> 
> `createPortal` already uses appendChild, so the element already appears at the right position.
> 
> `windowExists` should be sufficient, no `mounted` needed.
> 
> Breaking: The content of the modal will only be rendered if show = true.

In fact, it looks simpler than the old code. Did you test it for NextJS?

2023-05-26 04:31 UTC, tulup-conner requested changes
Thank you! Can you rebase and move these changes to `src/components/modal/*`? We just changed up our repository pretty substantially. You can see the new contributing guide here: https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md

If you aren't comfortable rebasing, let me know and I'll be happy to do so for you.

2023-05-26 04:31 UTC, tulup-conner commented on src/lib/components/Modal/Modal.tsx
> -        aria-hidden={!show}
Am I understanding correctly that you deleted this line because the element is no longer rendered at all in HTML once it is not "show"ing?

2023-05-26 07:32 UTC, tulup-conner commented
Yep happy to thanks again for working on this @myasteiner

2023-07-18 17:12 UTC, closed without merging