fix(modal): fixed a bug that disallowed users to set the position of a modal
themesberg/flowbite-react pull request #766
Opened 2023-05-25 20:07 UTC by rtraficante

## Description

The modal's position property is handled by the parent of the actual content box using flex, align-items, and justify-content but was blocked by the content box's property of "margin: auto" (m-auto). This fix deletes that property so the parent can correctly handle the position of the modal correctly.

Fixes #760 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I tested this change by running the documentation site locally and checking whether the property works correctly on the Modal component page.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-05-26 04:03 UTC, tulup-conner commented
Thank you! Can you move these changes to `src/theme.ts`? We just changed up our repository pretty substantially. You can see the new contributing guide here: https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md

2023-05-26 04:24 UTC, tulup-conner requested changes
Thank you! Can you rebase and move these changes to src/theme.ts? We just changed up our repository pretty substantially. You can see the new contributing guide here: https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md

If you aren't comfortable rebasing, let me know and I'll be happy to do so for you.

2023-05-26 06:07 UTC, rtraficante commented
@tulup-conner I'm like 96% sure I did that correctly

2023-05-30 10:59 UTC, rluders approved these changes

2023-05-30 20:00 UTC, merged

2023-07-31 14:59 UTC, Sagar160301 commented
Hey I have just used size props for modal
- for size **`sm`**, **`md`** and **`lg`** it is not working properly ( apart from this rest of size is working properly)
- I have used the latest of flowbite-react ( 0.5.0)
- please check this again