fix(pagination theme file): added enabled attribute for pagination ba…
themesberg/flowbite-react pull request #856
Opened 2023-07-14 00:06 UTC by kharbandaashu

fix #849 

**Description :** 

Hover class was getting applied even when button was disabled. so, added **enabled:** attribute to each hover class of pagination **base** theme. Now it will only show hover effect if button is enabled.

**Type of change:** 

tailwind css class attribute change.

**Breaking changes:**

No breaking change.

2023-07-14 07:40 UTC, tulup-conner requested changes
This looks good, but please edit your post by following the Pull Request template, which you can see here: https://github.com/themesberg/flowbite-react/blob/main/.github/PULL_REQUEST_TEMPLATE.md

2023-07-14 07:41 UTC, tulup-conner commented
Convert this back to ready for review once you've done that and I'll merge this

2023-07-14 13:06 UTC, kharbandaashu commented
> This looks good, but please edit your post by following the Pull Request template, which you can see here: https://github.com/themesberg/flowbite-react/blob/main/.github/PULL_REQUEST_TEMPLATE.md

Hey @tulup-conner , I changed the PR comments. This is the best I can do please let me know if it needs more improvement by sharing a sample PR.

2023-07-18 17:13 UTC, rluders approved these changes

2023-07-18 17:13 UTC, merged