Feat/kbd component to match flowbite library
themesberg/flowbite-react pull request #969
Opened 2023-09-17 19:30 UTC by MateoWartelle

- [X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

Summarize the changes made and the motivation behind them.

Reference related issues using `#` followed by the issue number.

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

2023-09-17 20:05 UTC, MateoWartelle commented
I am going to write some tests and it should be ready for review after. I am open to change whatever is suggested. 

thanks

2023-09-19 07:30 UTC, rluders commented
@MateoWartelle  please, do not use merge, use rebase instead.

2023-09-21 08:50 UTC, rluders requested changes

2023-09-21 08:50 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +## Arrow keys
I think the arrows are different from the flowbite documentation, aren't they? Is there any particular reason?

2023-09-21 08:50 UTC, rluders commented on app/data/components.tsx
> +    image: '/images/components/keyboard.svg',
Both images, default and dark are broken. You will need to add them to: https://github.com/themesberg/flowbite-react/tree/main/public/images/components

2023-09-21 09:21 UTC, SutuSebastian commented on app/docs/components/kbd/page.tsx
> +  title: 'React Forms - Flowbite',
Is the title correct in this one?

2023-09-21 09:56 UTC, rluders requested changes

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/index.tsx
> +      title="React Kbd - Flowbite"
React KBD (Keyboard) - Flowbite

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +The Kbd (Keyboard) component can be used to indicate a textual user input from the keyboard inside other elements such as in text, tables, cards, and more.
The KDB (Keyboard)

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +<CodePreview importFlowbiteReact="Kbd" title="Default Kbd">
Default KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +<CodePreview importFlowbiteReact="Kbd" title="Inside Text Kbd">
Inside Text KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +  title="Table Kbd"
Table KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +  title="Arrow Keys Kbd"
Arrow Keys KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +<CodePreview importFlowbiteReact="Kbd" title="Letter Keys Kbd">
Letter Keys KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +<CodePreview importFlowbiteReact="Kbd" title="Number Keys Kbd">
Number Keys KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +<CodePreview importFlowbiteReact="Kbd" title="Function Keys Kbd">
Function Keys KDB

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/page.tsx
> +    'Use the Kbd component as an inline element to denote textual user input from the keyboard inside paragraphs, tables, and other components',
Use the KDB ....

2023-09-21 09:56 UTC, rluders commented on app/docs/components/kbd/page.tsx
> +  title: 'React Forms - Flowbite',
React KBD (Keyboard) - Flowbite

2023-09-21 09:56 UTC, rluders commented
Looks nice, @MateoWartelle - just some small details that need to be fixed and we are good to get it merged.

2023-09-21 12:41 UTC, rluders commented on app/docs/components/kbd/kbd.mdx
> +## Arrow keys
🤔 I think that the standard flowbite library is now using the flowbite icons, but we don't support it yet. So, just ignore it and leave it as it is for now.

2023-09-21 16:47 UTC, merged