Feat/next js13/rsc support
themesberg/flowbite-react pull request #994
Opened 2023-09-24 17:37 UTC by SutuSebastian

- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

### Target
NextJS 13 App router and/or RSC support.

Reference related issues using `#` followed by the issue number.

### Breaking changes
- removal of `useTheme` react context provider for passing down `theme` to components
- TODO:

2023-09-25 08:14 UTC, rluders commented
This is going to be huge. o_O

2023-09-25 08:15 UTC, SutuSebastian commented
> This is going to be huge. o_O

Most definitely, but hopefully no changes when it comes to the end user.

2023-09-25 08:24 UTC, zoltanszogyenyi commented
> > This is going to be huge. o_O
> 
> Most definitely, but hopefully no changes when it comes to the end user.

That'd be the best outcome - no breaking changes other than documenting a new way of support SSC. Way to go!

2023-09-26 10:31 UTC, SutuSebastian commented
> @SutuSebastian just one tip here, don't use merge to get the changes from the main branch, use rebase. Otherwise, it will mess up with the commit history.

Good to know!

2023-10-02 07:43 UTC, rluders commented
@SutuSebastian you will need to rebase to remove the merges. Try to avoid merging, add the original flowbite-react repository like this as a second origin to your fork:

```sh
git remote add upstream https://github.com/themesberg/flowbite-react.git
```

Then you can get the changes from the original main to your branch just using the command:

```sh
git pull upstream main --rebase
```

2023-10-02 07:44 UTC, SutuSebastian commented
> @SutuSebastian you will need to rebase to remove the merges. Try to avoid merging, add the original flowbite-react repository like this as a second origin to your fork:
> 
> ```shell
> git remote add upstream https://github.com/themesberg/flowbite-react.git
> ```
> 
> Then you can get the changes from the original main to your branch just using the command:
> 
> ```shell
> git pull upstream main --rebase
> ```

I had to solve some conflicts, but from this point on I'll rebase. Thanks for the help!

2023-10-02 07:44 UTC, rluders commented
Also, you will probably have to remove the merge commits from your current PR, it will be a little bit painful. You probably will have to do some interactive rebase. You will need to remove/rebase:

[ef50757](https://github.com/themesberg/flowbite-react/pull/994/commits/ef50757540721dada216c1d2214de1611e155fdb)
[011b064](https://github.com/themesberg/flowbite-react/pull/994/commits/011b064b4e53a4632c8d7f34374e6cd1d24e5f10)
[0cfca32](https://github.com/themesberg/flowbite-react/pull/994/commits/0cfca32075fa84abea6609f7fddb0d896d03a917)

2023-10-02 18:24 UTC, rluders commented on src/components/FloatingLabel/index.ts
This is related to #1028

2023-10-02 18:25 UTC, rluders commented on src/components/Flowbite/FlowbiteTheme.ts
> +import type { FlowbiteFloatingLabelTheme } from '../FloatingLabel';
Also #1028

2023-10-02 18:29 UTC, rluders commented on src/components/FloatingLabel/index.ts
BTW, not saying to remove, it is just to keep track. :)

2023-10-02 18:39 UTC, SutuSebastian commented on src/components/FloatingLabel/index.ts
Nice, I was actually wondering where are the ticket issues for those

2023-10-05 07:36 UTC, rluders commented
@SutuSebastian I tested the branch with all my "huge" experience with NextJS and also with VIte. It seems to be working as expected. Of course, I didn't try all the components, and as we already discussed the fact that some/most of the components still use the `use client` directive probably will not make them work as SC. 

My main test was to see if there wasn't any broken related to the theme. As far as I noticed the only missing feature with the theme support now is the light/dark theme switching. Am I right? So, I think that, if we solve this we can get this PR merged and start to work/test the idea to remove the `use client` directive from the components that should be able to be used as SC.

But this is huge, and very nice work. So, let's finish it and get it merged, then we can work on some other minor features to introduce the SC rendering to the library.

2023-10-05 07:37 UTC, rluders commented
@tulup-conner @nigellima I would like to get some feedback from you folks.

2023-10-05 07:44 UTC, SutuSebastian commented
> @SutuSebastian I tested the branch with all my "huge" experience with NextJS and also with VIte. It seems to be working as expected. Of course, I didn't try all the components, and as we already discussed the fact that some/most of the components still use the `use client` directive probably will not make them work as SC.
> 
> My main test was to see if there wasn't any broken related to the theme. As far as I noticed the only missing feature with the theme support now is the light/dark theme switching. Am I right? So, I think that, if we solve this we can get this PR merged and start to work/test the idea to remove the `use client` directive from the components that should be able to be used as SC.
> 
> But this is huge, and very nice work. So, let's finish it and get it merged, then we can work on some other minor features to introduce the SC rendering to the library.

Sounds good!

Btw, we do have the theme switching, the hooks is called `useThemeMode`.

I also need to solve some conflicts as well, and "maybe" get the courage to rebase this branch without messing it up :D

2023-10-08 18:04 UTC, nigellima commented
> @tulup-conner @nigellima I would like to get some feedback from you folks.

Unfortunately my experience with Next is still minimum. I wish I could have a more solid experience so I could give good feedback here

2023-10-10 14:27 UTC, rluders requested changes

2023-10-10 14:40 UTC, SutuSebastian commented on src/helpers/use-watch-LS-value.ts
It is specific to watching a single value, that's why it's called like that, but I can rename it to `use-watch-localstorage-value.ts`, maybe it makes more sense 🤔

2023-10-10 14:46 UTC, rluders commented on src/helpers/use-watch-LS-value.ts
Please. :)

2023-10-10 15:03 UTC, rluders approved these changes

2023-10-10 15:31 UTC, merged

2023-10-13 09:12 UTC, rluders commented
For all those who are looking for NextJS RSC support, please, check our beta releases:
https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.3